#docker swarm join --token SWMTKN-1-4euwdyexk823rnfuocztdngowhwp175e0hpa9upv664gi25vtp-epuhq1pgn1k6on777njnw7n9o 192.168.100.10:2377

$script = <<-SCRIPT
  sudo apt-get update && \
  sudo apt-get install docker.io -y && \
  sudo apt-get update && \
  sudo apt-get install docker-compose -y
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "swarm_main" do |swarm_main|
    swarm_main.vm.network "forwarded_port", guest: 80, host: 8091
    swarm_main.vm.network "public_network", ip: "192.168.100.10"

    swarm_main.vm.provision "shell", inline: $script

    swarm_main.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu_bionic_swarm"
      vb.memory = 1024
      vb.cpus = 2
    end
  end

  config.vm.define "swarm_vm1" do |swarm_vm1|
    swarm_vm1.vm.network "forwarded_port", guest: 80, host: 8093
    swarm_vm1.vm.network "public_network", ip: "192.168.100.11"


    swarm_vm1.vm.provision "shell", inline: $script

    swarm_vm1.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu_bionic_swarm_vm1"
      vb.memory = 1024
      vb.cpus = 2
    end
  end

  config.vm.define "swarm_vm2" do |swarm_vm2|
    swarm_vm2.vm.network "forwarded_port", guest: 80, host: 8094
    swarm_vm2.vm.network "public_network", ip: "192.168.100.12"

    swarm_vm2.vm.provision "shell", inline: $script


    swarm_vm2.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu_bionic_swarm_vm2"
      vb.memory = 1024
      vb.cpus = 2
    end
  end

end
