version: "3.0"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  alurabooks:
    image: edvansanchoo/alura-books:1.0
    container_name: books-alura
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  
networks:
  compose-bridge:
    driver: bridge