# $script_mysql = <<-'SCRIPT'
#   apt-get update && \
#   apt-get install -y mysql-server && \
#   mysql -e "create user 'phpuser'@'%' identified by 'pass';"
# SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  # config.vm.define "mysqldb" do |mysql|
  #   mysql.vm.network "public_network", ip: "192.168.100.5"
  #
  #   mysql.vm.provision "shell",
  #     inline: "cat /configs/id_rsa.pub >> .ssh/authorized_keys"
  #   # mysql.vm.provision "shell", inline: $script_mysql
  #
  #   mysql.vm.synced_folder "./configs", "/configs"
  #   mysql.vm.synced_folder ".", "/vagrant", disabled: true
  # end

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "forwarded_port", guest: 80, host: 8089
    phpweb.vm.network "public_network", ip: "192.168.100.6"

    phpweb.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu_bionic_phpweb"
      vb.memory = 1024
      vb.cpus = 2
    end

    phpweb.vm.provision "shell",
      inline: "apt-get update && apt-get install -y puppet"

    phpweb.vm.provision "puppet" do |puppet|
       puppet.manifests_path = "./configs/manifest"
       puppet.manifest_file = "phpweb.pp"
    end
  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "192.168.100.7"

    mysqlserver.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu_bionic_mysqlserver"
      vb.memory = 1024
      vb.cpus = 2
    end

    mysqlserver.vm.provision "shell",
      inline: "cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.100.8"

    ansible.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu_bionic_ansible"
      vb.memory = 512
      vb.cpus = 1
    end

    ansible.vm.provision "shell",
      inline: "cp /vagrant/id_rsa /home/vagrant && \
               chmod 600 /home/vagrant/id_rsa && \
               chown vagrant:vagrant /home/vagrant/id_rsa"

    ansible.vm.provision "shell",
      inline: "apt-get update && \
               apt-get install -y software-properties-common && \
               apt-get install -y ansible"

     ansible.vm.provision "shell",
       inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                /vagrant/configs/ansible/playbook.yml"
  end

  config.vm.define "memcached" do |memcached|
    memcached.vm.box = "centos/7"
    memcached.vm.provider "virtualbox" do |vb|
      vb.name = "centos7_memcached"
      vb.memory = 512
      vb.cpus = 1
    end
  end
end
