---
- hosts: all
  tasks:
    - name: 'Instalar PHP5'
      apt:
        name: php5
        state: latest
      become: yes
    - name: 'Instalar o Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Instalar o modphp'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes
